print('hello, world!')
print(5+3)
print('python','is','fun!')
print('she said,\'hello!\'')
print('first line\nsecond line')
print('item 1\titem 2\t item 3')
print('the result is',42)
print(12345)
print(3.14159)
print('dollar sign:$')
print('apple','banana','cherry',sep=',')
print('hello,',end='')
print('world!')
print('python!'*3)
print('\u2764')
print()
print('hello'+'world!')
print(True)
print(False)
print(1.2e3)
print('''this is a multiline
print statement''')
print('this is a backslash:\\')